name: Publish Python ğŸ distributions ğŸ“¦ to TestPyPI

on:
  push:
    branches: [ continuous-integration ]
    tags:
      - '*.*.*'
      - run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      - run: poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_KEY }}
      - name: Publish package
        run: poetry publish --build -r testpypi
